services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    build:
      args:
        development: "true"
    volumes:
      - ../aiworkshop-bcapi-datasource/dist:/var/lib/grafana/plugins/aiworkshop-bcapi-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: aiworkshop-bcapi-datasource,aiworkshop-bcapi-app
      GF_INSTALL_PLUGINS: grafana-llm-app
