name: Build Workshop Image

on:
  push:
    paths:
      - '.docker/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: grafana/shared-workflows/actions/docker-build-push-image@main
        with:
          file: .docker/Dockerfile
          tags: |
            type=raw,value=latest
            type=sha,prefix={{date 'YYYYMMDD'}}-
          registries: dockerhub
          dockerhub-repository: grafana/grafana-con-2026-ai-inception-workshop
          platforms: linux/amd64
          push: 'true'